#!/bin/sh

set -e

case "$1" in
    postinst|configure)
        /usr/share/pve-no-subscription/no-subscription-warning.sh
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
